Traceback (most recent call last):
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dev = qml.device('default.qubit', shots=1000, wires=2, analytic=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mDeviceError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_1832/1915450117.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdev[0m [0;34m=[0m [0mqml[0m[0;34m.[0m[0mdevice[0m[0;34m([0m[0;34m'default.qubit'[0m[0;34m,[0m [0mshots[0m[0;34m=[0m[0;36m1000[0m[0;34m,[0m [0mwires[0m[0;34m=[0m[0;36m2[0m[0;34m,[0m [0manalytic[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/pennylane/__init__.py[0m in [0;36mdevice[0;34m(name, *args, **kwargs)[0m
[1;32m    261[0m [0;34m[0m[0m
[1;32m    262[0m         [0;31m# load device[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 263[0;31m         [0;32mreturn[0m [0mplugin_device_class[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0moptions[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    264[0m [0;34m[0m[0m
[1;32m    265[0m     [0;32mraise[0m [0mDeviceError[0m[0;34m([0m[0;34m"Device does not exist. Make sure the required plugin is installed."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/pennylane/devices/default_qubit.py[0m in [0;36m__init__[0;34m(self, wires, shots, cache, analytic)[0m
[1;32m    150[0m [0;34m[0m[0m
[1;32m    151[0m     [0;32mdef[0m [0m__init__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mwires[0m[0;34m,[0m [0;34m*[0m[0;34m,[0m [0mshots[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0manalytic[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 152[0;31m         [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mwires[0m[0;34m,[0m [0mshots[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m,[0m [0manalytic[0m[0;34m=[0m[0manalytic[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    153[0m [0;34m[0m[0m
[1;32m    154[0m         [0;31m# Create the initial state. Internally, we store the[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/pennylane/_qubit_device.py[0m in [0;36m__init__[0;34m(self, wires, shots, cache, analytic)[0m
[1;32m    123[0m [0;34m[0m[0m
[1;32m    124[0m     [0;32mdef[0m [0m__init__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mwires[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mshots[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0manalytic[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 125[0;31m         [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mwires[0m[0;34m=[0m[0mwires[0m[0;34m,[0m [0mshots[0m[0;34m=[0m[0mshots[0m[0;34m,[0m [0manalytic[0m[0;34m=[0m[0manalytic[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    126[0m [0;34m[0m[0m
[1;32m    127[0m         [0mself[0m[0;34m.[0m[0m_samples[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/pennylane/_device.py[0m in [0;36m__init__[0;34m(self, wires, shots, analytic)[0m
[1;32m    125[0m             [0mmsg[0m [0;34m=[0m [0;34m"The analytic argument has been replaced by shots=None. "[0m[0;34m[0m[0;34m[0m[0m
[1;32m    126[0m             [0mmsg[0m [0;34m+=[0m [0;34m"Please use shots=None instead of analytic=True."[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 127[0;31m             [0;32mraise[0m [0mDeviceError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    128[0m [0;34m[0m[0m
[1;32m    129[0m         [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mwires[0m[0;34m,[0m [0mIterable[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mDeviceError[0m: The analytic argument has been replaced by shots=None. Please use shots=None instead of analytic=True.
DeviceError: The analytic argument has been replaced by shots=None. Please use shots=None instead of analytic=True.

